import { describe, test, expect } from 'vitest'
import { cleanSessionTitle } from '../src/utils/sessionTitle'

describe('cleanSessionTitle', () => {
  test('strips a caveat block and keeps the real text after it', () => {
    const raw =
      '<local-command-caveat>Caveat: the messages below were generated by the user while running local commands.</local-command-caveat>Fix the sidebar tokens'
    expect(cleanSessionTitle(raw)).toBe('Fix the sidebar tokens')
  })

  test('strips a command-name/command-message pair down to nothing', () => {
    const raw = '<command-name>/effort</command-name><command-message>high</command-message>'
    expect(cleanSessionTitle(raw)).toBe('')
  })

  test('drops the untagged caveat boilerplate the session index stores', () => {
    const raw =
      'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to. Fix the sidebar tokens'
    expect(cleanSessionTitle(raw)).toBe('Fix the sidebar tokens')
  })

  test('drops the compaction-continuation preamble', () => {
    const raw =
      'This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation. ja is goed'
    expect(cleanSessionTitle(raw)).toBe('ja is goed')
  })

  test('leaves ordinary text unchanged', () => {
    expect(cleanSessionTitle('Refactor the sidebar tokens')).toBe('Refactor the sidebar tokens')
  })

  test('collapses internal whitespace', () => {
    expect(cleanSessionTitle('Fix   the   \n\n sidebar   tokens')).toBe('Fix the sidebar tokens')
  })

  test('truncates to max length with an ellipsis', () => {
    const long = 'a'.repeat(200)
    const result = cleanSessionTitle(long, 140)
    expect(result.length).toBe(141)
    expect(result.endsWith('…')).toBe(true)
    expect(result.startsWith('a'.repeat(140))).toBe(true)
  })

  test('returns an empty string for undefined input', () => {
    expect(cleanSessionTitle(undefined)).toBe('')
  })
})
