import { readFile, readdir, stat } from 'fs/promises'
import { createReadStream, watch, type FSWatcher } from 'fs'
import { createInterface } from 'readline'
import { join } from 'path'
import { homedir } from 'os'
import { BrowserWindow } from 'electron'

const isDev = process.env.NODE_ENV === 'development' || !!process.env.VITE_DEV_SERVER_URL

/** Session metadata extracted from JSONL transcript files */
export interface SessionIndexEntry {
  sessionId: string
  summary: string
  firstPrompt: string
  messageCount: number
  gitBranch: string
  modified: string
  created: string
  projectPath: string
  isSidechain: boolean
  filesModified: string[]
  filesRead: string[]
  toolCounts: Record<string, number>
  errorCount: number
  durationMs: number
  assistantMessageCount: number
  generatedTitle?: string
  generatedSummary?: string
}

/** Subset pushed to renderer for a terminal's summary */
export interface SessionSummaryData {
  summary: string
  firstPrompt: string
  messageCount: number
  gitBranch: string
  modified: string
}

/** Path to the hook-generated summary cache file */
const SUMMARY_CACHE_PATH = join(homedir(), '.claude', 'session-summaries.json')

/** Entry in the hook-generated summary cache file */
interface SummaryCacheEntry {
  title: string
  summary: string
  messageCount: number
  generatedAt: string
}

/**
 * Encode a project path the same way Claude Code does for its projects directory.
 */
export function encodeProjectPath(cwd: string): string {
  return cwd.replace(/[/\\\\:]/g, '-').replace(/^-/, '')
}

/**
 * Get the Claude projects directory for a given project path.
 */
function getProjectDir(projectPath: string): string {
  const encoded = encodeProjectPath(projectPath)
  return join(homedir(), '.claude', 'projects', encoded)
}

/**
 * Extract metadata from a single JSONL session file by reading only what we need.
 * Reads the first few lines for session info, then skips to count messages.
 */
async function parseSessionJsonl(filePath: string, projectPath: string): Promise<SessionIndexEntry | null> {
  try {
    const rl = createInterface({ input: createReadStream(filePath), crlfDelay: Infinity })

    let firstPrompt = ''
    let gitBranch = ''
    let created = ''
    let modified = ''
    let isSidechain = false
    let userMessageCount = 0
    let compactSummary = ''
    let assistantMessageCount = 0
    let errorCount = 0
    const filesModifiedSet = new Set<string>()
    const filesReadSet = new Set<string>()
    const toolCounts: Record<string, number> = {}

    for await (const line of rl) {
      if (!line) continue
      try {
        const obj = JSON.parse(line)

        // Track timestamps
        if (obj.timestamp) {
          if (!created) created = obj.timestamp
          modified = obj.timestamp
        }

        // System line often has metadata
        if (obj.type === 'system' && !gitBranch) {
          gitBranch = obj.gitBranch || ''
          if (obj.isSidechain) isSidechain = true
        }

        // First user message = firstPrompt
        if (obj.type === 'user') {
          userMessageCount++
          if (!firstPrompt) {
            const content = typeof obj.message === 'string' ? obj.message : (obj.message?.content || '')
            // Strip command tags for cleaner display
            firstPrompt = content.replace(/<command-[^>]*>[^<]*<\/command-[^>]*>\s*/g, '').trim().slice(0, 200)
            if (!gitBranch) gitBranch = obj.gitBranch || ''
          }

          // Count errors from tool_result blocks in user messages
          const userContent = obj.message?.content
          if (Array.isArray(userContent)) {
            for (const block of userContent) {
              if (block?.type === 'tool_result' && block.is_error) {
                errorCount++
              }
            }
          }
        }

        // Assistant messages: extract tool usage and file paths
        if (obj.type === 'assistant') {
          assistantMessageCount++
          const contentBlocks = obj.message?.content
          if (Array.isArray(contentBlocks)) {
            for (const block of contentBlocks) {
              if (block?.type === 'tool_use' && typeof block.name === 'string') {
                const toolName = block.name
                toolCounts[toolName] = (toolCounts[toolName] || 0) + 1

                const filePath = block.input?.file_path
                if (typeof filePath === 'string' && filePath) {
                  if (toolName === 'Edit' || toolName === 'Write') {
                    filesModifiedSet.add(filePath)
                  } else if (toolName === 'Read') {
                    filesReadSet.add(filePath)
                  }
                }
              }
            }
          }
        }

        // Compact summaries generated by Claude Code for context management
        if (obj.isCompactSummary) {
          const text = typeof obj.content === 'string' ? obj.content : (obj.message?.content || '')
          if (text) compactSummary = text.slice(0, 200)
        }
      } catch {
        // Skip malformed lines
      }
    }

    if (!firstPrompt && !compactSummary) return null

    // Compute duration from first to last timestamp
    let durationMs = 0
    if (created && modified && created !== modified) {
      const createdMs = new Date(created).getTime()
      const modifiedMs = new Date(modified).getTime()
      if (!isNaN(createdMs) && !isNaN(modifiedMs)) {
        durationMs = Math.max(0, modifiedMs - createdMs)
      }
    }

    const sessionId = filePath.replace(/^.*[\\/]/, '').replace('.jsonl', '')
    return {
      sessionId,
      summary: compactSummary || firstPrompt,
      firstPrompt,
      messageCount: userMessageCount,
      gitBranch,
      modified: modified || new Date().toISOString(),
      created: created || modified || new Date().toISOString(),
      projectPath,
      isSidechain,
      filesModified: Array.from(filesModifiedSet),
      filesRead: Array.from(filesReadSet),
      toolCounts,
      errorCount,
      durationMs,
      assistantMessageCount,
    }
  } catch {
    return null
  }
}

/**
 * Scans JSONL session files to build session metadata.
 * Falls back to sessions-index.json if available and fresh.
 *
 * sessions-index.json has been broken since Claude Code v2.1.31 (Feb 2026),
 * so JSONL parsing is the primary data source.
 */
export class SessionIndexService {
  private cache: Map<string, SessionIndexEntry> = new Map()
  private pendingProjectPath: string | null = null
  private activeReadPromise: Promise<void> | null = null
  private window: BrowserWindow
  private summaryCache: Record<string, SummaryCacheEntry> = {}
  private summaryCacheWatcher: FSWatcher | null = null
  private summaryCacheDebounceTimer: ReturnType<typeof setTimeout> | null = null
  /** Terminal-session pairs to push updates for when summary cache changes */
  private knownTerminalSessions: Array<{ terminalId: string; sessionId: string }> = []

  constructor(window: BrowserWindow) {
    this.window = window
    this.startWatchingSummaryCache()
  }

  /**
   * Load session data for a project by scanning JSONL files.
   * If a scan is already in progress, waits for it to complete instead of starting a new one.
   */
  async loadForProject(projectPath: string): Promise<void> {
    if (this.activeReadPromise) {
      this.pendingProjectPath = projectPath
      await this.activeReadPromise
      return
    }

    this.activeReadPromise = this.doScan(projectPath)
    try {
      await this.activeReadPromise
    } finally {
      this.activeReadPromise = null
    }
  }

  private async doScan(projectPath: string): Promise<void> {
    let pathToRead = projectPath
    do {
      this.pendingProjectPath = null
      await this.scanJsonlFiles(pathToRead)
      if (this.pendingProjectPath) {
        pathToRead = this.pendingProjectPath
      }
    } while (this.pendingProjectPath)
  }

  /**
   * Scan JSONL files in the project directory and populate the cache.
   * Only parses files that are newer than our cached version (incremental).
   */
  private async scanJsonlFiles(projectPath: string): Promise<void> {
    const dir = getProjectDir(projectPath)
    try {
      const files = await readdir(dir)
      const jsonlFiles = files.filter(f => f.endsWith('.jsonl'))

      if (jsonlFiles.length === 0) {
        this.cache.clear()
        return
      }

      // Get file stats to determine which files need parsing
      const fileStats = await Promise.all(
        jsonlFiles.map(async (f) => {
          const filePath = join(dir, f)
          const s = await stat(filePath).catch(() => null)
          return s ? { name: f, path: filePath, mtimeMs: s.mtimeMs } : null
        })
      )
      const validFiles = fileStats.filter((f): f is NonNullable<typeof f> => f !== null)

      // Remove cached entries for deleted files
      const currentIds = new Set(validFiles.map(f => f.name.replace('.jsonl', '')))
      for (const id of this.cache.keys()) {
        if (!currentIds.has(id)) this.cache.delete(id)
      }

      // Only parse files that are new or modified since last cache
      const filesToParse = validFiles.filter(f => {
        const sessionId = f.name.replace('.jsonl', '')
        const cached = this.cache.get(sessionId)
        if (!cached) return true
        // Re-parse if file was modified after our cached modified timestamp
        const cachedMs = new Date(cached.modified).getTime()
        return f.mtimeMs > cachedMs + 1000 // 1s tolerance
      })

      if (filesToParse.length > 0) {
        // Parse in batches of 10 to avoid overwhelming file handles
        const BATCH_SIZE = 10
        for (let i = 0; i < filesToParse.length; i += BATCH_SIZE) {
          const batch = filesToParse.slice(i, i + BATCH_SIZE)
          const results = await Promise.all(
            batch.map(f => parseSessionJsonl(f.path, projectPath))
          )
          for (const entry of results) {
            if (entry) this.cache.set(entry.sessionId, entry)
          }
        }
      }

      // Read and merge hook-generated summaries
      this.summaryCache = await this.readSummaryCache()
      this.mergeSummaryCacheIntoEntries()

      if (isDev) {
        console.log(`[SessionIndex] ${this.cache.size} sessions (parsed ${filesToParse.length} new/updated) for ${projectPath}`)
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        this.cache.clear()
      } else if (isDev) {
        console.error('[SessionIndex] Scan error:', err)
      }
    }
  }

  /**
   * Read the hook-generated summary cache file.
   * Returns empty object if file doesn't exist or is corrupt.
   */
  private async readSummaryCache(): Promise<Record<string, SummaryCacheEntry>> {
    try {
      const content = await readFile(SUMMARY_CACHE_PATH, 'utf-8')
      const parsed = JSON.parse(content)
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as Record<string, SummaryCacheEntry>
      }
      return {}
    } catch {
      // File doesn't exist, is corrupt, or unreadable — graceful fallback
      return {}
    }
  }

  /**
   * Merge hook-generated summaries into cached session entries.
   */
  private mergeSummaryCacheIntoEntries(): void {
    for (const [sessionId, cacheEntry] of Object.entries(this.summaryCache)) {
      const entry = this.cache.get(sessionId)
      if (entry && cacheEntry.title && cacheEntry.summary) {
        entry.generatedTitle = cacheEntry.title
        entry.generatedSummary = cacheEntry.summary
      }
    }
  }

  /**
   * Start watching the hook-generated summary cache file for changes.
   * Uses fs.watch with debounce to handle atomic writes (temp+rename).
   */
  private startWatchingSummaryCache(): void {
    try {
      this.summaryCacheWatcher = watch(SUMMARY_CACHE_PATH, (eventType) => {
        if (eventType === 'change' || eventType === 'rename') {
          this.debouncedSummaryCacheUpdate()
        }
      })
      // Handle watcher errors gracefully (file may not exist yet)
      this.summaryCacheWatcher.on('error', () => {
        // File may not exist yet — try again later by re-creating watcher
        this.stopWatchingSummaryCache()
        setTimeout(() => this.startWatchingSummaryCache(), 10000)
      })
    } catch {
      // fs.watch can throw if file doesn't exist — retry later
      setTimeout(() => this.startWatchingSummaryCache(), 10000)
    }
  }

  private stopWatchingSummaryCache(): void {
    if (this.summaryCacheWatcher) {
      this.summaryCacheWatcher.close()
      this.summaryCacheWatcher = null
    }
    if (this.summaryCacheDebounceTimer) {
      clearTimeout(this.summaryCacheDebounceTimer)
      this.summaryCacheDebounceTimer = null
    }
  }

  /**
   * Debounced handler for summary cache file changes.
   * Ignores changes within 1 second of each other.
   */
  private debouncedSummaryCacheUpdate(): void {
    if (this.summaryCacheDebounceTimer) {
      clearTimeout(this.summaryCacheDebounceTimer)
    }
    this.summaryCacheDebounceTimer = setTimeout(() => {
      this.summaryCacheDebounceTimer = null
      void this.onSummaryCacheChanged()
    }, 1000)
  }

  /**
   * Handle summary cache file change: re-read cache, merge into entries, push updates.
   */
  private async onSummaryCacheChanged(): Promise<void> {
    this.summaryCache = await this.readSummaryCache()
    this.mergeSummaryCacheIntoEntries()

    // Push updated summaries/titles to renderer for known terminal-session pairs
    for (const { terminalId, sessionId } of this.knownTerminalSessions) {
      this.pushSummaryToRenderer(terminalId, sessionId)
    }
  }

  /**
   * Register terminal-session pairs for receiving summary cache updates.
   */
  registerTerminalSessions(pairs: Array<{ terminalId: string; sessionId: string }>): void {
    this.knownTerminalSessions = pairs
  }

  /**
   * Get summary data for a specific session ID.
   */
  getSessionSummary(sessionId: string): SessionSummaryData | undefined {
    const entry = this.cache.get(sessionId)
    if (!entry) return undefined
    return {
      summary: entry.summary,
      firstPrompt: entry.firstPrompt,
      messageCount: entry.messageCount,
      gitBranch: entry.gitBranch,
      modified: entry.modified,
    }
  }

  /**
   * Get all cached entries sorted by modified date (newest first).
   */
  getRecentSessions(limit = 20): SessionIndexEntry[] {
    return Array.from(this.cache.values())
      .sort((a, b) => new Date(b.modified).getTime() - new Date(a.modified).getTime())
      .slice(0, limit)
  }

  /**
   * Get sessions for a specific project path (on-demand scan).
   * Used by the sessions panel and project overview.
   */
  async getSessionsForProject(projectPath: string, limit = 20): Promise<SessionIndexEntry[]> {
    await this.loadForProject(projectPath)
    return this.getRecentSessions(limit)
  }

  /**
   * Push summary update for a specific terminal to the renderer.
   * Prefers hook-generated summary/title over raw JSONL data.
   */
  pushSummaryToRenderer(terminalId: string, sessionId: string): void {
    const entry = this.cache.get(sessionId)
    if (!entry) return

    // Prefer generated summary over compact/firstPrompt
    const displaySummary = entry.generatedSummary || entry.summary || entry.firstPrompt || ''
    if (displaySummary) {
      this.sendToRenderer('terminal:summary', terminalId, displaySummary)
    }

    // Push generated title if available
    if (entry.generatedTitle) {
      this.sendToRenderer('terminal:generated-title', terminalId, entry.generatedTitle)
    }
  }

  /**
   * Re-scan and push updated summaries for all known terminal-session pairs.
   */
  async refreshAndPush(
    projectPath: string,
    terminalSessions: Array<{ terminalId: string; sessionId: string }>
  ): Promise<void> {
    // Keep track of known pairs so fs.watch can push updates
    this.knownTerminalSessions = terminalSessions
    await this.loadForProject(projectPath)
    for (const { terminalId, sessionId } of terminalSessions) {
      this.pushSummaryToRenderer(terminalId, sessionId)
    }
  }

  private sendToRenderer(channel: string, ...args: unknown[]): void {
    if (this.window && !this.window.isDestroyed()) {
      this.window.webContents.send(channel, ...args)
    }
  }

  destroy(): void {
    this.stopWatchingSummaryCache()
    this.cache.clear()
    this.pendingProjectPath = null
    this.knownTerminalSessions = []
  }
}
