import { readFile, readdir, stat } from 'fs/promises'
import { createReadStream } from 'fs'
import { createInterface } from 'readline'
import { join } from 'path'
import { homedir } from 'os'
import { BrowserWindow } from 'electron'

const isDev = process.env.NODE_ENV === 'development' || !!process.env.VITE_DEV_SERVER_URL

/** Session metadata extracted from JSONL transcript files */
export interface SessionIndexEntry {
  sessionId: string
  summary: string
  firstPrompt: string
  messageCount: number
  gitBranch: string
  modified: string
  created: string
  projectPath: string
  isSidechain: boolean
}

/** Subset pushed to renderer for a terminal's summary */
export interface SessionSummaryData {
  summary: string
  firstPrompt: string
  messageCount: number
  gitBranch: string
  modified: string
}

/**
 * Encode a project path the same way Claude Code does for its projects directory.
 */
export function encodeProjectPath(cwd: string): string {
  return cwd.replace(/[/\\\\:]/g, '-').replace(/^-/, '')
}

/**
 * Get the Claude projects directory for a given project path.
 */
function getProjectDir(projectPath: string): string {
  const encoded = encodeProjectPath(projectPath)
  return join(homedir(), '.claude', 'projects', encoded)
}

/**
 * Extract metadata from a single JSONL session file by reading only what we need.
 * Reads the first few lines for session info, then skips to count messages.
 */
async function parseSessionJsonl(filePath: string, projectPath: string): Promise<SessionIndexEntry | null> {
  try {
    const rl = createInterface({ input: createReadStream(filePath), crlfDelay: Infinity })

    let firstPrompt = ''
    let gitBranch = ''
    let created = ''
    let modified = ''
    let isSidechain = false
    let userMessageCount = 0
    let compactSummary = ''

    for await (const line of rl) {
      if (!line) continue
      try {
        const obj = JSON.parse(line)

        // Track timestamps
        if (obj.timestamp) {
          if (!created) created = obj.timestamp
          modified = obj.timestamp
        }

        // System line often has metadata
        if (obj.type === 'system' && !gitBranch) {
          gitBranch = obj.gitBranch || ''
          if (obj.isSidechain) isSidechain = true
        }

        // First user message = firstPrompt
        if (obj.type === 'user') {
          userMessageCount++
          if (!firstPrompt) {
            const content = typeof obj.message === 'string' ? obj.message : (obj.message?.content || '')
            // Strip command tags for cleaner display
            firstPrompt = content.replace(/<command-[^>]*>[^<]*<\/command-[^>]*>\s*/g, '').trim().slice(0, 200)
            if (!gitBranch) gitBranch = obj.gitBranch || ''
          }
        }

        // Compact summaries generated by Claude Code for context management
        if (obj.isCompactSummary) {
          const text = typeof obj.content === 'string' ? obj.content : (obj.message?.content || '')
          if (text) compactSummary = text.slice(0, 200)
        }
      } catch {
        // Skip malformed lines
      }
    }

    if (!firstPrompt && !compactSummary) return null

    const sessionId = filePath.replace(/^.*[\\/]/, '').replace('.jsonl', '')
    return {
      sessionId,
      summary: compactSummary || firstPrompt,
      firstPrompt,
      messageCount: userMessageCount,
      gitBranch,
      modified: modified || new Date().toISOString(),
      created: created || modified || new Date().toISOString(),
      projectPath,
      isSidechain,
    }
  } catch {
    return null
  }
}

/**
 * Scans JSONL session files to build session metadata.
 * Falls back to sessions-index.json if available and fresh.
 *
 * sessions-index.json has been broken since Claude Code v2.1.31 (Feb 2026),
 * so JSONL parsing is the primary data source.
 */
export class SessionIndexService {
  private cache: Map<string, SessionIndexEntry> = new Map()
  private pendingProjectPath: string | null = null
  private activeReadPromise: Promise<void> | null = null
  private window: BrowserWindow

  constructor(window: BrowserWindow) {
    this.window = window
  }

  /**
   * Load session data for a project by scanning JSONL files.
   * If a scan is already in progress, waits for it to complete instead of starting a new one.
   */
  async loadForProject(projectPath: string): Promise<void> {
    if (this.activeReadPromise) {
      this.pendingProjectPath = projectPath
      await this.activeReadPromise
      return
    }

    this.activeReadPromise = this.doScan(projectPath)
    try {
      await this.activeReadPromise
    } finally {
      this.activeReadPromise = null
    }
  }

  private async doScan(projectPath: string): Promise<void> {
    let pathToRead = projectPath
    do {
      this.pendingProjectPath = null
      await this.scanJsonlFiles(pathToRead)
      if (this.pendingProjectPath) {
        pathToRead = this.pendingProjectPath
      }
    } while (this.pendingProjectPath)
  }

  /**
   * Scan JSONL files in the project directory and populate the cache.
   * Only parses files that are newer than our cached version (incremental).
   */
  private async scanJsonlFiles(projectPath: string): Promise<void> {
    const dir = getProjectDir(projectPath)
    try {
      const files = await readdir(dir)
      const jsonlFiles = files.filter(f => f.endsWith('.jsonl'))

      if (jsonlFiles.length === 0) {
        this.cache.clear()
        return
      }

      // Get file stats to determine which files need parsing
      const fileStats = await Promise.all(
        jsonlFiles.map(async (f) => {
          const filePath = join(dir, f)
          const s = await stat(filePath).catch(() => null)
          return s ? { name: f, path: filePath, mtimeMs: s.mtimeMs } : null
        })
      )
      const validFiles = fileStats.filter((f): f is NonNullable<typeof f> => f !== null)

      // Remove cached entries for deleted files
      const currentIds = new Set(validFiles.map(f => f.name.replace('.jsonl', '')))
      for (const id of this.cache.keys()) {
        if (!currentIds.has(id)) this.cache.delete(id)
      }

      // Only parse files that are new or modified since last cache
      const filesToParse = validFiles.filter(f => {
        const sessionId = f.name.replace('.jsonl', '')
        const cached = this.cache.get(sessionId)
        if (!cached) return true
        // Re-parse if file was modified after our cached modified timestamp
        const cachedMs = new Date(cached.modified).getTime()
        return f.mtimeMs > cachedMs + 1000 // 1s tolerance
      })

      if (filesToParse.length > 0) {
        // Parse in batches of 10 to avoid overwhelming file handles
        const BATCH_SIZE = 10
        for (let i = 0; i < filesToParse.length; i += BATCH_SIZE) {
          const batch = filesToParse.slice(i, i + BATCH_SIZE)
          const results = await Promise.all(
            batch.map(f => parseSessionJsonl(f.path, projectPath))
          )
          for (const entry of results) {
            if (entry) this.cache.set(entry.sessionId, entry)
          }
        }
      }

      if (isDev) {
        console.log(`[SessionIndex] ${this.cache.size} sessions (parsed ${filesToParse.length} new/updated) for ${projectPath}`)
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
        this.cache.clear()
      } else if (isDev) {
        console.error('[SessionIndex] Scan error:', err)
      }
    }
  }

  /**
   * Get summary data for a specific session ID.
   */
  getSessionSummary(sessionId: string): SessionSummaryData | undefined {
    const entry = this.cache.get(sessionId)
    if (!entry) return undefined
    return {
      summary: entry.summary,
      firstPrompt: entry.firstPrompt,
      messageCount: entry.messageCount,
      gitBranch: entry.gitBranch,
      modified: entry.modified,
    }
  }

  /**
   * Get all cached entries sorted by modified date (newest first).
   */
  getRecentSessions(limit = 20): SessionIndexEntry[] {
    return Array.from(this.cache.values())
      .sort((a, b) => new Date(b.modified).getTime() - new Date(a.modified).getTime())
      .slice(0, limit)
  }

  /**
   * Get sessions for a specific project path (on-demand scan).
   * Used by the sessions panel and project overview.
   */
  async getSessionsForProject(projectPath: string, limit = 20): Promise<SessionIndexEntry[]> {
    await this.loadForProject(projectPath)
    return this.getRecentSessions(limit)
  }

  /**
   * Push summary update for a specific terminal to the renderer.
   */
  pushSummaryToRenderer(terminalId: string, sessionId: string): void {
    const summary = this.getSessionSummary(sessionId)
    if (summary) {
      const displaySummary = summary.summary || summary.firstPrompt || ''
      if (displaySummary) {
        this.sendToRenderer('terminal:summary', terminalId, displaySummary)
      }
    }
  }

  /**
   * Re-scan and push updated summaries for all known terminal-session pairs.
   */
  async refreshAndPush(
    projectPath: string,
    terminalSessions: Array<{ terminalId: string; sessionId: string }>
  ): Promise<void> {
    await this.loadForProject(projectPath)
    for (const { terminalId, sessionId } of terminalSessions) {
      this.pushSummaryToRenderer(terminalId, sessionId)
    }
  }

  private sendToRenderer(channel: string, ...args: unknown[]): void {
    if (this.window && !this.window.isDestroyed()) {
      this.window.webContents.send(channel, ...args)
    }
  }

  destroy(): void {
    this.cache.clear()
    this.pendingProjectPath = null
  }
}
