/**
 * Session titles/summaries in the project overview come straight from
 * Claude Code's session index, which can carry raw tool/system markup —
 * caveat blocks, slash-command tags, etc. — that was never meant to be
 * shown to a human. This strips that markup so the overview reads as
 * plain text (see docs/plan/2026-09-04-design-overhaul.html, "Projectoverzicht").
 */

// Matches a tag and everything between its open/close pair, including the
// content — e.g. <local-command-caveat>Caveat: …</local-command-caveat> or
// <command-name>/effort</command-name>. Case-insensitive, non-greedy, and
// repeated via the `g` flag to strip multiple/nested blocks.
const TAG_BLOCK = /<([a-zA-Z][\w-]*)\b[^>]*>[\s\S]*?<\/\1>/gi

// Any remaining standalone tag (open, close or self-closing) with no pair.
const LOOSE_TAG = /<\/?[a-zA-Z][\w-]*\b[^>]*>/g

// System boilerplate that Claude Code injects as (or in front of) a user's
// first prompt. The session index often stores it with the tags already
// stripped, so the block regex above never sees it — match the sentences.
const BOILERPLATE: readonly RegExp[] = [
  // Tolerates a truncated tail (the index caps prompts) — `$` closes the match.
  /Caveat: The messages below were generated by the user while running local commands\.[^.<]*(?:\.|$|(?=<))(?:[^.<]*explicitly asks you to\.)?/gi,
  /This session is being continued from a previous conversation that ran out of context\.(?:\s*The summary below covers the earlier portion of the conversation\.)?/gi,
]

export function cleanSessionTitle(raw: string | undefined, max = 140): string {
  if (!raw) return ''

  let text = raw
  // Tag blocks can nest or repeat; strip until stable (bounded by a max
  // number of passes so malformed input can't loop forever).
  for (let i = 0; i < 5; i++) {
    const next = text.replace(TAG_BLOCK, ' ')
    if (next === text) break
    text = next
  }
  text = text.replace(LOOSE_TAG, ' ')
  // After the markup: catches the same boilerplate stored without its tags.
  for (const re of BOILERPLATE) text = text.replace(re, ' ')

  text = text.replace(/\s+/g, ' ').trim()

  if (text.length > max) {
    text = text.slice(0, max).trimEnd() + '…'
  }

  return text
}
